PipelineSecrets:
  DockerConfig: '{"auths":{"braidplume.azurecr.io":{"auth":"YnJhaWRwbHVtZTpLbERpUzZsUCs2dEZ5MlB3bmt4SnNCcnI2TW0xc2VYVw=="}}}'
cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --v
  - 4
  config:
    domain: 40.118.104.50.nip.io
    exposer: Ingress
    http: "true"
jenkins:
  Servers:
    Global:
      EnvVars:
        DOCKER_REGISTRY: braidplume.azurecr.io
        TILLER_NAMESPACE: kube-system
prow: {}
